name: 'MS Teams Notification'
description: 'Send a notification to Microsoft Teams'
author: 'Tu Nombre o Empresa'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  webhook_url:
    description: 'The webhook URL for Microsoft Teams'
    required: true
  message:
    description: 'The message to send'
    required: true
  notify_on:
    description: 'When to send notifications (success, failure, both)'
    required: false
    default: 'both'
  job_status:
    description: 'Status of the GitHub Actions job (success or failure)'
    required: true
  environment:
    description: 'Deployment environment (e.g., production, staging, development)'
    required: false
    default: 'Not Set'
  custom_fields:
    description: 'Custom JSON object with additional fields'
    required: false
    default: '{}'

runs:
  using: 'node16'
  main: 'dist/index.js'
